version: '3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: checkout1
      MYSQL_PASSWORD: test1234
    ports:
      - "3306:3306"
